import type { Metadata } from "next";
import { Header } from "@/ui/Header";
import "./globals.css";
import { Footer } from "@/ui/Footer";
import { ToastManager } from "@/ui/toast/ToastManager";

export const metadata: Metadata = {
  title: "Ecom DM",
  //description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`antialiased min-h-screen flex flex-col`}>
        <ToastManager />
        {/*<Provider>*/}
        <Header />
        <main className="grow">{children}</main>
        <Footer />
        {/*</Provider>*/}
      </body>
    </html>
  );
}
