import type { Metadata } from "next";
import { Header } from "@/ui/Header";
import "./globals.css";
import { Footer } from "@/ui/Footer";
import { ToastManager } from "@/ui/toast/ToastManager";
import { KeycloakProvider } from "../context/KeycloakContext";

export const metadata: Metadata = {
  title: "Ecom DM",
  //description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`antialiased min-h-screen flex flex-col`}>
        <ToastManager />
        <KeycloakProvider>
          <Header />
          <main className="grow">{children}</main>
          <Footer />
        </KeycloakProvider>
      </body>
    </html>
  );
}
